language: objective-c
os: osx
osx_image: xcode9.2
env: TERM=dumb SHLVL=0
git:
  submodules: true
script:
  - "( brew install libsodium json-c )"
  - "( ./lib/bin/build_libsodium-macos )"
  - "( cd ./platform-independent/cli-c && ./clean && targets='mpw mpw-bench mpw-tests' ./build && ./mpw-tests && ./mpw-cli-tests )"
  - "( cd ./gradle && ./gradlew --info clean test )"
  - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword iOS' -sdk iphonesimulator )"
  - "( xcodebuild -workspace platform-darwin/MasterPassword.xcworkspace -configuration 'Test' -scheme 'MasterPassword macOS' )"
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGxodW5hdGglM0FseW5kaXIuY29tLyUyMWR2S1JpaW1uc0Z3dWdseEpHSyUzQWx5bmRpci5jb20"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never

